name: CI Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: 'Install Dependancies'
        run: npm ci
      - name: 'Run Linter'
        run: npm run lint
  # unit-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup Node 12.x
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '12.x'
  #     - name: 'Install Dependancies'
  #       run: npm ci
  #     - name: 'Run Unit Tests'
  #       run: npm run test:ci -- --coverage